services:
  # Backend nginx server for Nginx Proxy Manager
  nginx-backend:
    image: nginx:alpine
    container_name: dcs-nginx-backend
    restart: unless-stopped
    volumes:
      - ./nginx-backend.conf:/etc/nginx/nginx.conf:ro
      - ../dcs-stats:/var/www/html:ro
    depends_on:
      - php
    networks:
      - dcs_network

  # PHP-FPM with security hardening
  php:
    image: php:8.2-fpm-alpine
    container_name: dcs-php-secure
    restart: unless-stopped
    volumes:
      - ../dcs-stats:/var/www/html
      - ./php-security.ini:/usr/local/etc/php/conf.d/99-security.ini:ro
      - ./php-fpm-security.conf:/usr/local/etc/php-fpm.d/zz-security.conf:ro
    environment:
      - REDIS_HOST=redis
      - PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-256M}
    depends_on:
      - redis
    networks:
      - dcs_network

  # Redis with security
  redis:
    image: redis:7-alpine
    container_name: dcs-redis-secure
    restart: unless-stopped
    command: redis-server --maxmemory ${REDIS_MEMORY_LIMIT:-256mb} --maxmemory-policy allkeys-lru
    networks:
      - dcs_network

  # Nginx Proxy Manager with Web UI
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: dcs-nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'        # Public HTTP Port
      - '443:443'      # Public HTTPS Port
      - '81:81'        # Admin Web Port
    environment:
      # Database configuration (uses SQLite by default if not set)
      DB_MYSQL_HOST: ${NPM_DB_MYSQL_HOST:-}
      DB_MYSQL_PORT: ${NPM_DB_MYSQL_PORT:-3306}
      DB_MYSQL_USER: ${NPM_DB_MYSQL_USER:-}
      DB_MYSQL_PASSWORD: ${NPM_DB_MYSQL_PASSWORD:-}
      DB_MYSQL_NAME: ${NPM_DB_MYSQL_NAME:-}
      # IPv6 configuration
      DISABLE_IPV6: ${NPM_DISABLE_IPV6:-}
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    depends_on:
      - nginx-backend
    networks:
      - dcs_network

networks:
  dcs_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: dcs_br0

volumes:
  npm_data:
    driver: local
  npm_letsencrypt:
    driver: local